version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
