PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdo: <https://schema.org/>

SELECT DISTINCT ?subject ?label WHERE {
  { ?subject sdo:name ?label }
  UNION
  { ?subject rdfs:label ?label }
}
LIMIT 100
