# List identifiers and titles of Amateur Film Platform items
PREFIX sdo: <https://schema.org/>

SELECT DISTINCT ?series_id ?program_id ?program_title
WHERE {
  GRAPH <http://data.rdlabs.beeldengeluid.nl/cat/> {
    ?series_id a sdo:CreativeWorkSeries ; sdo:additionalType ?series_additional_type .
    FILTER(CONTAINS(?series_additional_type, 'smalfilm'))
    ?program_id sdo:partOfSeries ?series_id ;      
                sdo:name ?program_title .
  }
}
LIMIT 10