# Amateur Film collection item identifiers (available online)
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX sdo: <https://schema.org/>

SELECT DISTINCT ?s
WHERE {
  GRAPH <http://data.rdlabs.beeldengeluid.nl/cat/> {
    {
      ?s sdo:partOfSeries/sdo:additionalType "Bewegend beeld - Smalfilm"^^sdo:Text .
    }
    UNION
    {
      ?s sdo:additionalType "Bewegend beeld - Smalfilm"^^sdo:Text .
    }
  }
  ?s a sdo:CreativeWork .
  
  # Filter items available online on General Public Portal.
  ?s sdo:conditionsOfAccess ?show_browse
  FILTER(CONTAINS(?show_browse, 'True'))
}