# Amateur Film collection items
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX sdo: <https://schema.org/>

SELECT DISTINCT ?s ?title
WHERE {
  GRAPH <http://data.rdlabs.beeldengeluid.nl/cat/> {
    {
      ?s sdo:partOfSeries/sdo:additionalType "Bewegend beeld - Smalfilm"^^sdo:Text .
    }
    UNION
    {
      ?s sdo:additionalType "Bewegend beeld - Smalfilm"^^sdo:Text .
    }
  }
s  OPTIONAL {
    ?s sdo:name ?program_title
  }
  BIND(STR(COALESCE(?program_title, 'Untitled'^^xsd:string)) AS ?title)
}