# Onderdelen van een programma (scenes)
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX sdo: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Select all scene description for a program
SELECT DISTINCT ?s ?program_title ?scene_description ?scene_title
WHERE {
  VALUES ?s {
    <http://data.beeldengeluid.nl/id/program/2101608190180567031>
  }

  ?s rdf:type sdo:CreativeWork ;
           sdo:name ?program_title ;
           sdo:hasPart ?scene_description .
  ?scene_description sdo:name ?scene_title.

}
#LIMIT 10
