# Handelsplaten collection item identifiers
# Datasource: https://cat.apis.beeldengeluid.nl/sparql

PREFIX sdo: <https://schema.org/>

SELECT (COUNT(DISTINCT ?s) AS ?cnt)
WHERE {
VALUES ?series {<http://data.beeldengeluid.nl/id/series/2101608030026064731>}
?s sdo:partOfSeason/sdo:partOfSeries ?series 
}