# Online te bekijken/beluisteren (via the GPP)
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX sdo: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Toon alleen items die ook op GPP te bekijken/beluisteren zijn.
SELECT DISTINCT ?item 
WHERE {
  ?item rdf:type sdo:CreativeWork .
  ?item sdo:conditionsOfAccess ?show_browse
  FILTER(CONTAINS(?show_browse, 'True'))
} LIMIT 10