PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdo: <https://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX gtaa: <http://data.beeldengeluid.nl/gtaa/>

SELECT DISTINCT ?programId ?title ?gtaa_concept ?person_name_pref_label
WHERE {
  VALUES ?person_name_uri {gtaa:164629}  # note: edit the GTAA URI

  ?programId a sdo:CreativeWork .
  ?programId (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer)/
 (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer) ?person_name_uri .
  ?programId sdo:name ?program_title .
  ?programId sdo:partOfSeries/sdo:name ?series_title
  BIND(
    COALESCE(
      IF(?program_title, ?program_title, 1/0),
      IF(?series_title, ?series_title, 1/0),
      "Unknown"
    ) AS ?title
  )
} LIMIT 100