# Items over bepaald onderwerp, die online afspeelbaar zijn
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sdo: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

# Toon alleen items die ook op GPP te bekijken/beluisteren zijn.
SELECT DISTINCT ?item ?url_gpp ?prefLabel
WHERE {
  VALUES ?prefLabel {
    \"invasies\"@nl
    #    \"Jodenvervolging\"@nl
    #  \"Tweede Wereldoorlog\"@nl
  }
  ?item rdf:type sdo:CreativeWork .
  ?item sdo:conditionsOfAccess ?show_browse .
  ?item sdo:url ?url_gpp .
  ?item (sdo:about|sdo:mentions)/skos:prefLabel ?prefLabel
  FILTER(CONTAINS(?show_browse, 'True'))
} 
LIMIT 10