# Online te bekijken/beluisteren (via the GPP)
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX sdo: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT ?item 
WHERE {
  ?item rdf:type sdo:CreativeWork ;
        sdo:conditionsOfAccess "View/listen to media online at the item's URL: True"^^xsd:string .
} LIMIT 10