# Aan een onderwerp gerelateerde items, die online afspeelbaar zijn (via de GPP)
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX sdo: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX gtaa: <http://data.beeldengeluid.nl/gtaa/>

SELECT DISTINCT ?item ?url_gpp ?title ?license
WHERE {
  VALUES ?onderwerp {gtaa:27098}  # note: edit the concept id
  ?item rdf:type sdo:CreativeWork ;
        (sdo:about|sdo:mentions) ?onderwerp ;
        sdo:name ?title ;
        sdo:url ?url_gpp ;
        sdo:license ?license ;
        sdo:conditionsOfAccess ?show_browse .

  # Toon alleen items die ook op GPP te bekijken/beluisteren zijn.
  FILTER(CONTAINS(?show_browse, 'True'))
}
LIMIT 100