# Locations related to a program
# Datasource: https://cat.apis.beeldengeluid.nl/sparql

PREFIX sdo: <https://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?location ?locationName
WHERE {
VALUES ?program_uri {<http://data.beeldengeluid.nl/id/program/2101608040029461531>}
  ?program_uri sdo:about ?location .
  ?location skos:inScheme <http://data.beeldengeluid.nl/gtaa/GeografischeNamen> ;
            skos:prefLabel ?locationName
} 
LIMIT 10