# MOZ Concerts
# Datasource: https://cat.apis.beeldengeluid.nl/sparql

PREFIX sdo: <https://schema.org/>

# Show the ID and title of all concerts that are part of the Dutch Broadcast Concert (MOZ) collection, in alphabetical order
SELECT DISTINCT ?programUri ?programName
WHERE {
   ?series sdo:name "Muziekopnamen Zendgemachtigden (MOZ)"^^xsd:string .
   ?programUri sdo:partOfSeason/sdo:partOfSeries ?series . 
   ?programUri sdo:name ?programName . 
   }  ORDER BY ?programName