# Onderwerpen voor een persoon
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdo: <https://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT ?keyword
WHERE {
  ?s (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer)/
  (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer) ?personId .

  ?personId skos:prefLabel \"Bouwman, Mies\"@nl . 

  ?s sdo:about ?subjectIri . 

  ?subjectIri skos:prefLabel ?keyword 
}
