# Personen voor een programma
# Datasource: http://54.217.179.144/sparql
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdo: <https://schema.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

# Personen voor een programma (ook via series/seizoen/scene description)

SELECT ?entity ?entityName where {
  {
    <http://data.rdlabs.beeldengeluid.nl/id/program/2101608160143012931> a sdo:CreativeWork ;
      (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer)/
      (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer) ?entity  .
    
    ?entity skos:prefLabel ?entityName 
  }
  
  UNION
  {
    <http://data.rdlabs.beeldengeluid.nl/id/program/2101608160143012931> sdo:isPartOfSeason ?season .

    ?season  (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer)/
    (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer) ?entity  .
  
    ?entity skos:prefLabel ?entityName 
  }
  
  UNION
  {
    <http://data.rdlabs.beeldengeluid.nl/id/program/2101608160143012931> sdo:isPartOfSeason/
    sdo:isPartOfSeries ?series . 

    ?series  (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer)/
    (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer) ?entity  .
  
    ?entity skos:prefLabel ?entityName 
  }
  
  UNION
  {
    ?scene sdo:hasPart <http://data.rdlabs.beeldengeluid.nl/id/program/2101608160143012931> .

    ?scene  (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer)/
    (sdo:about|sdo:mentions|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer) ?entity  .

    ?entity skos:prefLabel ?entityName 
  }
}
