# Select persons related to a person via a program in the catalogue
# Datasource: https://cat.apis.beeldengeluid.nl/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX sdo: <https://schema.org/>
PREFIX gtaa: <http://data.beeldengeluid.nl/gtaa/>

# Select persons related to a person via a program in the catalogue
SELECT DISTINCT ?other_person_uri ?other_person_name 
WHERE {
  VALUES ?persoons_namen_uri {gtaa:126347}  # note: edit the GTAA URI
  ?programId a sdo:CreativeWork .

  ?programId (sdo:about|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer)/
  (sdo:about|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer) gtaa:126347 .

  ?programId (sdo:about|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer)/
  (sdo:about|sdo:creator|sdo:contributor|sdo:actor|sdo:crew|sdo:performer) ?other_person_uri .

  ?other_person_uri skos:prefLabel ?other_person_name .
  FILTER(?other_person_uri != ?persoons_namen_uri)
}