# Search in full text for thesaurus term
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX gtaa:<http://data.beeldengeluid.nl/gtaa/>

SELECT DISTINCT ?s ?pref_label ?concept_scheme
WHERE {
    VALUES ?query { "oorlog" }
  ?s (skos:prefLabel|skos:altLabel|skos:hiddenLabel) ?label .
  ?s skos:prefLabel ?pref_label .
    ?s skos:inScheme ?concept_scheme
  FILTER regex(?label, ?query, "i" )
}
