# Items related to 'Tweede Wereldoorlog' (WOII), that are playable online (via GPP)
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX sdo: <https://schema.org/>
PREFIX gtaa: <http://data.beeldengeluid.nl/gtaa/>
SELECT DISTINCT ?s ?url_gpp ?title
WHERE {
  VALUES ?wo2 {gtaa:72531} # "Tweede Wereldoorlog" (part of ConceptScheme 'Namen')
    ?s sdo:about ?wo2 ;
       sdo:name ?title ;
       sdo:url ?url_gpp ;
       sdo:conditionsOfAccess "View/listen to media online at the item's URL: True"^^xsd:string .
}
LIMIT 100