# Select subject terms related with narrower relation
# Datasource: https://cat.apis.beeldengeluid.nl/sparql

PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX gtaa:<http://data.beeldengeluid.nl/gtaa/>

# Select subject terms related with narrower relation
SELECT DISTINCT ?narrow_term ?pref_label ?concept_scheme
WHERE {
    VALUES ?onderwerp { gtaa:27098 }
    ?onderwerp skos:narrower ?narrow_term .
    ?narrow_term skos:prefLabel ?pref_label ;
        skos:inScheme ?concept_scheme
}