# Describe a SKOS Concept (briefly)
# Datasource: https://cat.apis.beeldengeluid.nl/sparql

PREFIX gtaa:<http://data.beeldengeluid.nl/gtaa/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX skosxl: <http://www.w3.org/2008/05/skos-xl#>

# Describe a SKOS Concept (briefly)
SELECT *
WHERE {
  VALUES ?uri {gtaa:72531}
  ?uri skos:prefLabel ?pref_label .
  OPTIONAL {
    ?uri skosxl:altLabel/skosxl:literalForm ?alt_label .
  }
  OPTIONAL {
    ?uri skos:scopeNote ?scope_note .
  }
  OPTIONAL {
    ?uri skos:inScheme ?concept_scheme
  }
}
