PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sdo: <https://schema.org/>

# geef de titel informatie van het programma (indien aanwezig) en indien er hierarchische relaties zijn de
# titels die bij het seizoen of de serie horen (van CreativeWorkSeason of CreativeWorkSeries).

SELECT ?program_id ?title ?series_title ?season_title
WHERE {
  ?program_id sdo:name ?title
  OPTIONAL {
    ?program_id sdo:partOfSeries ?series_id.
    ?series_id sdo:name ?series_title
  }
  OPTIONAL {
    ?program_id sdo:partOfSeason ?season_id.
    ?season_id sdo:name ?season_title
  }
}
LIMIT 10
