# Show a program title from catalogue, plus (optionally) the series/season title.
# Datasource: https://cat.apis.beeldengeluid.nl/sparql

PREFIX sdo: <https://schema.org/>

# Show a program title from catalogue, plus (optionally) the series/season title.
SELECT ?s ?title ?series_title ?season_title
WHERE {
  GRAPH <http://data.rdlabs.beeldengeluid.nl/cat/> {
  ?s sdo:name ?title
  OPTIONAL {
    ?s sdo:partOfSeries ?series_id.
    ?series_id sdo:name ?series_title
  }
  OPTIONAL {
    ?s sdo:partOfSeason ?season_id.
    ?season_id sdo:name ?season_title
  }
  }
}
LIMIT 10