# Toon alle aanwezige licenties en rechten statements
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX sdo: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?license
WHERE {
  ?item rdf:type sdo:CreativeWork .
  ?item sdo:license ?license .
}
