# Show all distinct licenses and rights statements in use.
# Datasource: https://cat.apis.beeldengeluid.nl/sparql
PREFIX sdo: <https://schema.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

# Show all distinct licenses and rights statements in use.
SELECT DISTINCT ?license
WHERE {
  ?s rdf:type sdo:CreativeWork .
  ?s sdo:license ?license .
}
