# Belgian software
# Datasource: https://dbpedia.org/sparql
SELECT ?software ?company WHERE {
  ?software dbpedia-owl:developer ?company.
  ?company dbpedia-owl:locationCountry [ rdfs:label "Belgium"@en ].
}
