# Carpenters killed by crucifixion
# Datasource: https://dbpedia.org/sparql
PREFIX yago: <http://dbpedia.org/class/yago/>
SELECT ?person
WHERE {
  ?person a yago:Carpenters, yago:PeopleExecutedByCrucifixion.
}
