# People who have something in common with Jesus
# Datasource: https://dbpedia.org/sparql
SELECT DISTINCT ?person
WHERE {
  dbpedia:Jesus dc:subject ?common.
  ?person a foaf:Person;
          dc:subject ?common.
}
LIMIT 1000
